language: node_js
node_js:
  - "8.11.1"
  - "7"

before_script:
  - npm install -g gulp-cli
  
script:
  - gulp

jobs:
  include:
    - stage: deploy
      node_js: 8.11.1
      script: skip
      deploy:
        provider: azure_web_apps
        site: nodesample
        verbose: true
      on: master
        
